package com.studious.display;

import com.studious.dao.LessonDAO;
import com.studious.dao.QuestionDAO;
import com.studious.dao.QuestionOfTestDAO;
import com.studious.dao.TeacherDAO;
import com.studious.dao.TestDAO;
import com.studious.entity.Lesson;
import com.studious.entity.QuestionOfTest;
import com.studious.entity.Teacher;
import com.studious.entity.Test;
import com.studious.utils.Auth;
import com.studious.utils.XImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phan Qui Duc
 */
public class TestList extends javax.swing.JFrame {

    JFrame window = null;

    public TestList() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Studious - Danh sách bài thi thử");
        setIconImage(XImage.getAppIcon());
        fillCboSubjectList(true);
        fillTblTestList("");
        tblTestList.setAutoCreateRowSorter(true);
    }

    public TestList(JFrame window) {
        this.window = window;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Studious - Danh sách bài thi thử");
        setIconImage(XImage.getAppIcon());
        fillCboSubjectList(true);
        fillTblTestList("");
        tblTestList.setAutoCreateRowSorter(true);
    }
    private String testID;
    private int timeTest;
    private TestDAO tDao = new TestDAO();
    private QuestionOfTestDAO qotDAO = new QuestionOfTestDAO();



    //hàm cập nhật giá trị đầu vào:
    private void setTime() {
        if (!cboTestTypeList.getSelectedItem().equals("THPTQG")) {
            timeTest = Integer.valueOf(cboTestTypeList.getSelectedItem().toString().substring(0, 2));
        } else {
            String subject = (String) cboSubjectList.getSelectedItem();
            switch (subject) {
                case "Toán" -> {
                    timeTest = 90;
                }
                case "Vật Lý","Hóa Học","Sinh Học","Lịch Sử","Địa Lý","Giáo Dục Công Dân" -> {
                    timeTest = 50;
                }
                case "Tiếng Anh" ->
                    timeTest = 50;
                default ->
                    throw new AssertionError();
            }
        }

    }
    
    private void fillTblTestList (String testTitle) {
        DefaultTableModel model = (DefaultTableModel) tblTestList.getModel();
        model.setRowCount(0);
        List<Test> testList = null;
        if (testTitle.isBlank()) {
            testList = tDao.selectBySubjectAndTime((String) cboSubjectList.getSelectedItem(), timeTest);
        }
        else {
            testList = tDao.selectBtTestTitleAndSubjectAndTime(testTitle, (String) cboSubjectList.getSelectedItem(), timeTest);
        }
        if (testList != null) {
            for (int i = 0; i < testList.size(); i++) {
                Test get = testList.get(i);
                List<QuestionOfTest> questionOfTestList = qotDAO.selectByTestId(get.getTestID());
                Integer numberOfQuests = questionOfTestList.size();
                Teacher teacher = new TeacherDAO().selectById(get.getTeacherID());
                model.addRow(new Object[]{i + 1, get.getTestID(), get.getTestTitle(), get.getTimeTest(), get.getCreateDate(), teacher.getFullname(), numberOfQuests});
            }
        }
    }
    
    private void fillCboSubjectList (boolean check) {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cboSubjectList.getModel();
            model.removeAllElements();
            if (check) {
                model.addElement("Toán");
                model.addElement("Vật Lý");
                model.addElement("Hóa Học");
                model.addElement("Sinh Học");
                model.addElement("Ngữ Văn");
                model.addElement("Lịch Sử");
                model.addElement("Địa Lý");
                model.addElement("Giáo Dục Công Dân");
                model.addElement("Tiếng Anh");
            }
            else {
                model.addElement("Toán");
                model.addElement("Vật Lý");
                model.addElement("Hóa Học");
                model.addElement("Sinh Học");
                model.addElement("Lịch Sử");
                model.addElement("Địa Lý");
                model.addElement("Giáo Dục Công Dân");
                model.addElement("Tiếng Anh");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTestList = new javax.swing.JTable();
        btnSearchList = new javax.swing.JButton();
        txtSearchList = new javax.swing.JTextField();
        cboSubjectList = new javax.swing.JComboBox<>();
        cboTestTypeList = new javax.swing.JComboBox<>();
        lblTestTypeList = new javax.swing.JLabel();
        lblSubjectList = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        jToolBar = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        btnPersonalInfo = new javax.swing.JButton();
        btnLessons1 = new javax.swing.JButton();
        btnTest1 = new javax.swing.JButton();
        btnScore1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlBackground.setBackground(new java.awt.Color(232, 255, 183));
        pnlBackground.setForeground(new java.awt.Color(232, 255, 183));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnStart.setBackground(new java.awt.Color(221, 221, 221));
        btnStart.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/icons8-pencil-24 (1).png"))); // NOI18N
        btnStart.setText("Làm");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        tblTestList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã đề thi", "Tên bài thi", "Thời gian", "Ngày tạo", "Người tạo", "Số lượng câu hỏi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTestList.getTableHeader().setReorderingAllowed(false);
        tblTestList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTestListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTestList);

        btnSearchList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/icons8-search-24.png"))); // NOI18N
        btnSearchList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchListActionPerformed(evt);
            }
        });

        txtSearchList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cboSubjectList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboSubjectList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toán" }));
        cboSubjectList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSubjectListItemStateChanged(evt);
            }
        });
        cboSubjectList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubjectListActionPerformed(evt);
            }
        });

        cboTestTypeList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTestTypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15 Phút", "45 Phút", "60 Phút", "THPTQG" }));
        cboTestTypeList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTestTypeListItemStateChanged(evt);
            }
        });
        cboTestTypeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTestTypeListActionPerformed(evt);
            }
        });

        lblTestTypeList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTestTypeList.setText("Loại bài thi:");
        lblTestTypeList.setToolTipText("");

        lblSubjectList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubjectList.setText("Môn:");
        lblSubjectList.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 592, Short.MAX_VALUE)
                        .addComponent(btnStart))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSearchList, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchList))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSubjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTestTypeList, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboTestTypeList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTestTypeList)
                    .addComponent(cboTestTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchList)
                    .addComponent(btnSearchList, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnStart)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblTitle.setBackground(new java.awt.Color(232, 255, 183));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(47, 106, 1));
        lblTitle1.setText("DANH SÁCH BÀI THI THỬ");

        lblTitle2.setBackground(new java.awt.Color(232, 255, 183));
        lblTitle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/Studious-255x68.png"))); // NOI18N

        jToolBar.setBackground(new java.awt.Color(232, 255, 183));
        jToolBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 255, 183)));
        jToolBar.setFloatable(false);
        jToolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar.setRollover(true);

        btnHome.setBackground(new java.awt.Color(232, 255, 183));
        btnHome.setForeground(new java.awt.Color(232, 255, 183));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/home.png"))); // NOI18N
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setMaximumSize(new java.awt.Dimension(45, 45));
        btnHome.setMinimumSize(new java.awt.Dimension(45, 45));
        btnHome.setPreferredSize(new java.awt.Dimension(45, 45));
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jToolBar.add(btnHome);

        btnPersonalInfo.setBackground(new java.awt.Color(232, 255, 183));
        btnPersonalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/account.png"))); // NOI18N
        btnPersonalInfo.setFocusable(false);
        btnPersonalInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersonalInfo.setMaximumSize(new java.awt.Dimension(45, 45));
        btnPersonalInfo.setMinimumSize(new java.awt.Dimension(45, 45));
        btnPersonalInfo.setPreferredSize(new java.awt.Dimension(45, 45));
        btnPersonalInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPersonalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoActionPerformed(evt);
            }
        });
        jToolBar.add(btnPersonalInfo);

        btnLessons1.setBackground(new java.awt.Color(232, 255, 183));
        btnLessons1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/lessons.png"))); // NOI18N
        btnLessons1.setFocusable(false);
        btnLessons1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLessons1.setMaximumSize(new java.awt.Dimension(45, 45));
        btnLessons1.setMinimumSize(new java.awt.Dimension(45, 45));
        btnLessons1.setPreferredSize(new java.awt.Dimension(45, 45));
        btnLessons1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLessons1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLessons1ActionPerformed(evt);
            }
        });
        jToolBar.add(btnLessons1);

        btnTest1.setBackground(new java.awt.Color(232, 255, 183));
        btnTest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/mockExam.png"))); // NOI18N
        btnTest1.setFocusable(false);
        btnTest1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTest1.setMaximumSize(new java.awt.Dimension(45, 45));
        btnTest1.setMinimumSize(new java.awt.Dimension(45, 45));
        btnTest1.setPreferredSize(new java.awt.Dimension(45, 45));
        btnTest1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest1ActionPerformed(evt);
            }
        });
        jToolBar.add(btnTest1);

        btnScore1.setBackground(new java.awt.Color(232, 255, 183));
        btnScore1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/score.png"))); // NOI18N
        btnScore1.setFocusable(false);
        btnScore1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnScore1.setMaximumSize(new java.awt.Dimension(45, 45));
        btnScore1.setMinimumSize(new java.awt.Dimension(45, 45));
        btnScore1.setPreferredSize(new java.awt.Dimension(45, 45));
        btnScore1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnScore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScore1ActionPerformed(evt);
            }
        });
        jToolBar.add(btnScore1);

        btnBack.setBackground(new java.awt.Color(232, 255, 183));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setFocusable(false);
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.setMaximumSize(new java.awt.Dimension(45, 45));
        btnBack.setMinimumSize(new java.awt.Dimension(45, 45));
        btnBack.setPreferredSize(new java.awt.Dimension(45, 45));
        btnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jToolBar.add(btnBack);

        btnLogout.setBackground(new java.awt.Color(232, 255, 183));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/logout.png"))); // NOI18N
        btnLogout.setToolTipText("");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(45, 45));
        btnLogout.setMinimumSize(new java.awt.Dimension(45, 45));
        btnLogout.setPreferredSize(new java.awt.Dimension(45, 45));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar.add(btnLogout);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblTitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTitle)
                        .addGap(9, 9, 9)
                        .addComponent(lblTitle1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnStartActionPerformed

    private void tblTestListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTestListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTestListMouseClicked

    private void btnSearchListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchListActionPerformed
        // TODO add your handling code here:
        fillTblTestList(txtSearchList.getText());
    }//GEN-LAST:event_btnSearchListActionPerformed

    private void cboSubjectListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSubjectListItemStateChanged

    }//GEN-LAST:event_cboSubjectListItemStateChanged

    private void cboSubjectListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubjectListActionPerformed
        // TODO add your handling code here:
        setTime();
        fillTblTestList("");
    }//GEN-LAST:event_cboSubjectListActionPerformed

    private void cboTestTypeListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTestTypeListItemStateChanged
        
    }//GEN-LAST:event_cboTestTypeListItemStateChanged

    private void cboTestTypeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTestTypeListActionPerformed
        // TODO add your handling code here:
        String testType = (String) cboTestTypeList.getSelectedItem();
        switch (testType) {
            case "15 Phút","45 Phút","60 Phút" -> {
                fillCboSubjectList(true);
            }
            case "THPTQG" -> {
                fillCboSubjectList(false);
            }
            default ->
                throw new AssertionError();
        }
        setTime();
    }//GEN-LAST:event_cboTestTypeListActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Login.main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPersonalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoActionPerformed
        PersonalInforStudent window = new PersonalInforStudent(this, true);
        window.setVisible(true);
    }//GEN-LAST:event_btnPersonalInfoActionPerformed

    private void btnLessons1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLessons1ActionPerformed
        LessonsStudent window = new LessonsStudent(this);
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLessons1ActionPerformed

    private void btnTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest1ActionPerformed
        TestList window = new TestList(this);
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTest1ActionPerformed

    private void btnScore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScore1ActionPerformed
        ScoreBoardStudent window = new ScoreBoardStudent(this, true);
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnScore1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Auth.user = null;
        Login window = new Login();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Login.main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLessons1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPersonalInfo;
    private javax.swing.JButton btnScore1;
    private javax.swing.JButton btnSearchList;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnTest1;
    private javax.swing.JComboBox<String> cboSubjectList;
    private javax.swing.JComboBox<String> cboTestTypeList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JLabel lblSubjectList;
    private javax.swing.JLabel lblTestTypeList;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTable tblTestList;
    private javax.swing.JTextField txtSearchList;
    // End of variables declaration//GEN-END:variables
}
