/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.studious.display;

import com.studious.dao.ResutlDAO;
import com.studious.entity.Result;
import com.studious.utils.XImage;
import java.util.List;

/**
 *
 * @author Admin
 */
public class TestReport extends javax.swing.JDialog {

    /**
     * Creates new form TestReport
     */
    public TestReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DoTest.clock.stop();
        initComponents();
        setLocationRelativeTo(null);
        init();
    }
    
    ResutlDAO rDao = new ResutlDAO();
    List<Result> listResult = rDao.selectByIndexTest(DoTest.sEntity.getStudentID(), DoTest.testEntity.getTestID(), DoTest.indexTest);
    int sumQuestion = listResult.size();
    double eachPoint = 10.0 / sumQuestion;
    int sumCorrect = 0;
    int sumSelected = 0;
    double sumPoint = 0;
    
    private void init() {
        setTitle("Studious - Báo cáo bài thi");
        setIconImage(XImage.getAppIcon());
        calculateReport();
        fillReport();
        vote();
    }

    public void fillReport() {
        lblTimeNumber.setText(DoTest.timeTested + " phút");
        lblScoreNumber.setText(sumPoint + " điểm");
        lblRightAnswerNumber.setText(sumCorrect + "/" + sumQuestion);
        lblDoneAnswerNumber.setText(sumSelected + "/" + sumQuestion);
    }

    public void calculateReport() {
        for (Result result : listResult) {
            if (!result.getAnsSelected().equals("")) {
                sumSelected++;
                if (result.getAnsSelected().equals(result.getAnsCorrect())) {
                    sumCorrect++;
                }
            }
        }
        sumPoint = sumCorrect * eachPoint;
        System.out.println(eachPoint);
    }

    public void vote() {
        if (sumPoint >= 9) {
            lblShowRate.setText("Xuất sắc");
        } else if (sumPoint >= 8) {
            lblShowRate.setText("Giỏi");
        } else if (sumPoint >= 6) {
            lblShowRate.setText("Khá");
        } else if (sumPoint >= 4) {
            lblShowRate.setText("Trung bình");
        } else {
            lblShowRate.setText("Yếu");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitleReport = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblTimeNumber = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblScoreNumber = new javax.swing.JLabel();
        lblRightAnswer = new javax.swing.JLabel();
        lblRightAnswerNumber = new javax.swing.JLabel();
        lblDoneAnswer = new javax.swing.JLabel();
        lblDoneAnswerNumber = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        lblShowRate = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlBackground.setBackground(new java.awt.Color(232, 255, 183));

        lblLogo.setBackground(new java.awt.Color(232, 255, 183));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/studious/icons/Studious-255x68.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleReport.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        lblTitleReport.setForeground(new java.awt.Color(47, 106, 1));
        lblTitleReport.setText("BÁO CÁO BÀI THI");

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTime.setText("Thời gian hoàn thành:");

        lblTimeNumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTimeNumber.setText("40 phút");

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblScore.setText("Điểm:");

        lblScoreNumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblScoreNumber.setText("9 điểm");

        lblRightAnswer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRightAnswer.setText("Số câu trả lời đúng:");

        lblRightAnswerNumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRightAnswerNumber.setText("45/50");

        lblDoneAnswer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDoneAnswer.setText("Số câu đã trả lời:");

        lblDoneAnswerNumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDoneAnswerNumber.setText("50/50");

        lblRate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRate.setText("Đánh giá:");

        lblShowRate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblShowRate.setText("Xuất sắc");

        btnReturn.setBackground(new java.awt.Color(229, 229, 229));
        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReturn.setText("Trở về");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lblTitleReport))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime)
                            .addComponent(lblScore)
                            .addComponent(lblRightAnswer)
                            .addComponent(lblDoneAnswer)
                            .addComponent(lblRate))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblScoreNumber)
                            .addComponent(lblTimeNumber)
                            .addComponent(lblRightAnswerNumber)
                            .addComponent(lblDoneAnswerNumber)
                            .addComponent(lblShowRate)
                            .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitleReport)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(lblTimeNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScore)
                    .addComponent(lblScoreNumber))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRightAnswer)
                    .addComponent(lblRightAnswerNumber))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoneAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoneAnswerNumber))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowRate))
                .addGap(41, 41, 41)
                .addComponent(btnReturn)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        lblTitle.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(47, 106, 1));
        lblTitle.setText("LÀM BÀI THI THỬ");

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(46, 46, 46)
                        .addComponent(lblTitle))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTitle)))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        Login.main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Login.main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TestReport dialog = new TestReport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDoneAnswer;
    private javax.swing.JLabel lblDoneAnswerNumber;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblRightAnswer;
    private javax.swing.JLabel lblRightAnswerNumber;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreNumber;
    private javax.swing.JLabel lblShowRate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleReport;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
